// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DownloadModel(arg1:string):Promise<boolean>;

export function GetModels():Promise<Array<main.Model>>;

export function LoadFile():Promise<string>;

export function ProcessFile(arg1:string):Promise<string>;

export function SetActiveModel(arg1:string):Promise<void>;
